<a href="https://colab.research.google.com/github/Shubhu123k12/PERFORM-ANALYSIS-ON-A-LARGE-DATASET-USING-TOOLS-LIKE-PYSPARK-OR-DASK-TO-DEMONSTRATE-SCALABILITY/blob/main/Internship_Task-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("/original_cleaned_nyc_taxi_data_2018.csv")

In [5]:
df.head(10)

,Unnamed: 0,trip_distance,rate_code,store_and_fwd_flag,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,...,total_amount,pickup_location_id,dropoff_location_id,year,month,day,day_of_week,hour_of_day,trip_duration,calculated_total_amount
0,3,16.97,1,N,1,49.5,0.0,0.5,5.61,5.76,...,61.67,231,138.0,2018.0,3.0,29.0,3.0,13.0,3317.0,61.67
1,4,14.45,1,N,1,45.5,0.0,0.5,10.41,5.76,...,62.47,87,138.0,2018.0,3.0,29.0,3.0,14.0,3648.0,62.47
2,5,11.60,1,N,1,42.0,0.0,0.5,14.57,5.76,...,63.13,68,138.0,2018.0,3.0,29.0,3.0,14.0,3540.0,63.13
3,10,5.10,1,N,1,26.5,1.0,0.5,5.65,0.00,...,33.95,186,33.0,2018.0,3.0,29.0,3.0,16.0,2585.0,33.95
4,12,11.11,1,N,1,45.5,1.0,0.5,10.61,5.76,...,63.67,163,138.0,2018.0,3.0,29.0,3.0,16.0,4521.0,63.67
5,13,9.54,1,N,1,41.0,1.0,0.5,9.71,5.76,...,58.27,138,244.0,2018.0,3.0,29.0,3.0,16.0,3738.0,58.27
6,17,10.00,1,N,1,38.5,1.0,0.5,8.05,0.00,...,48.35,138,25.0,2018.0,3.0,29.0,3.0,17.0,3598.0,48.35
7,18,9.80,1,N,1,38.5,1.0,0.5,6.94,5.76,...,53.00,138,90.0,2018.0,3.0,29.0,3.0,17.0,3267.0,53.00
8,20,14.10,1,N,1,48.5,1.0,0.5,7.00,5.76,...,63.06,264,264.0,2018.0,3.0,29.0,3.0,17.0,3959.0,63.06
9,23,18.50,1,N,1,50.0,0.5,0.5,15.35,0.00,...,66.65,132,255.0,2018.0,5.0,19.0,5.0,0.0,1512.0,66.65